"""initial schema

Revision ID: a2094de88a4c
Revises: 
Create Date: 2026-06-08 15:18:08.755998

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a2094de88a4c'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categoria_empresa',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('slug', sa.String(length=40), nullable=False),
    sa.Column('nome', sa.String(length=80), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('usuario',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('nome', sa.String(length=120), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('senha_hash', sa.Text(), nullable=False),
    sa.Column('perfil', sa.String(length=20), nullable=False),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.Column('criado_em', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("perfil IN ('admin', 'editor', 'pesquisador', 'gestor')", name='ck_usuario_perfil'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('audit_log',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('tabela', sa.String(length=60), nullable=False),
    sa.Column('registro_id', sa.UUID(), nullable=False),
    sa.Column('usuario_id', sa.UUID(), nullable=True),
    sa.Column('operacao', sa.String(length=10), nullable=False),
    sa.Column('campo_alterado', sa.String(length=80), nullable=True),
    sa.Column('valor_anterior', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('valor_novo', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('criado_em', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("operacao IN ('INSERT', 'UPDATE', 'DELETE')", name='ck_audit_log_operacao'),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuario.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('empresa',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('categoria_id', sa.Integer(), nullable=False),
    sa.Column('nome_fantasia', sa.String(length=120), nullable=False),
    sa.Column('razao_social', sa.String(length=120), nullable=True),
    sa.Column('cnpj', sa.String(length=18), nullable=True),
    sa.Column('endereco', sa.String(length=200), nullable=True),
    sa.Column('bairro', sa.String(length=80), nullable=True),
    sa.Column('telefone', sa.String(length=20), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('status', sa.String(length=10), server_default='ativo', nullable=False),
    sa.Column('data_baixa', sa.Date(), nullable=True),
    sa.Column('aceita_pesquisas', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('contato_pesquisas', sa.String(length=120), nullable=True),
    sa.Column('telefone_pesquisas', sa.String(length=20), nullable=True),
    sa.Column('email_pesquisas', sa.String(length=120), nullable=True),
    sa.Column('proprietario', sa.String(length=200), nullable=True),
    sa.Column('campos_extras', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('criado_em', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('atualizado_em', sa.DateTime(), nullable=True),
    sa.Column('criado_por', sa.UUID(), nullable=True),
    sa.CheckConstraint("status IN ('ativo', 'inativo')", name='ck_empresa_status'),
    sa.ForeignKeyConstraint(['categoria_id'], ['categoria_empresa.id'], ),
    sa.ForeignKeyConstraint(['criado_por'], ['usuario.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('formulario_versao',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('ano', sa.Integer(), nullable=False),
    sa.Column('schema_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('status', sa.String(length=10), server_default='ativo', nullable=False),
    sa.Column('criado_em', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('criado_por', sa.UUID(), nullable=True),
    sa.CheckConstraint("status IN ('ativo', 'travado')", name='ck_formulario_versao_status'),
    sa.ForeignKeyConstraint(['criado_por'], ['usuario.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ano')
    )
    op.create_table('periodo_ocupacao',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('tipo', sa.String(length=15), nullable=False),
    sa.Column('descricao', sa.String(length=100), nullable=False),
    sa.Column('data_inicio', sa.Date(), nullable=False),
    sa.Column('data_fim', sa.Date(), nullable=False),
    sa.Column('status', sa.String(length=15), server_default='aberto', nullable=False),
    sa.Column('protocolo', sa.String(length=10), nullable=True),
    sa.Column('criado_em', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('criado_por', sa.UUID(), nullable=True),
    sa.CheckConstraint("status IN ('aberto', 'encerrado', 'publicado')", name='ck_periodo_ocupacao_status'),
    sa.CheckConstraint("tipo IN ('consolidado', 'expectativa')", name='ck_periodo_ocupacao_tipo'),
    sa.ForeignKeyConstraint(['criado_por'], ['usuario.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('respondente_pesquisa',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('empresa_id', sa.UUID(), nullable=False),
    sa.Column('periodo_id', sa.Integer(), nullable=True),
    sa.Column('tipo_pesquisa', sa.String(length=30), nullable=False),
    sa.Column('protocolo', sa.String(length=10), nullable=True),
    sa.Column('respondeu', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('data_resposta', sa.DateTime(), nullable=True),
    sa.Column('observacao', sa.Text(), nullable=True),
    sa.CheckConstraint("tipo_pesquisa IN ('taxa_ocupacao', 'demanda')", name='ck_respondente_tipo_pesquisa'),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresa.id'], ),
    sa.ForeignKeyConstraint(['periodo_id'], ['periodo_ocupacao.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('resposta_demanda',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('formulario_versao_id', sa.Integer(), nullable=False),
    sa.Column('pesquisador_id', sa.UUID(), nullable=False),
    sa.Column('parque', sa.String(length=20), nullable=False),
    sa.Column('coletado_em', sa.DateTime(), nullable=False),
    sa.Column('sync_status', sa.String(length=15), server_default='sincronizado', nullable=False),
    sa.Column('alerta_coerencia', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('descricao_alerta', sa.Text(), nullable=True),
    sa.CheckConstraint("parque IN ('thermas', 'rubio', 'hot_beach', 'dolce_dulce')", name='ck_resposta_demanda_parque'),
    sa.ForeignKeyConstraint(['formulario_versao_id'], ['formulario_versao.id'], ),
    sa.ForeignKeyConstraint(['pesquisador_id'], ['usuario.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('resposta_ocupacao',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('periodo_id', sa.Integer(), nullable=False),
    sa.Column('empresa_id', sa.UUID(), nullable=False),
    sa.Column('taxa_ocupacao', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('uhs_informadas', sa.Integer(), nullable=True),
    sa.Column('leitos_informados', sa.Integer(), nullable=True),
    sa.Column('diaria_media', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('respondido_em', sa.DateTime(), nullable=True),
    sa.Column('respondido_por', sa.UUID(), nullable=True),
    sa.Column('observacao', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresa.id'], ),
    sa.ForeignKeyConstraint(['periodo_id'], ['periodo_ocupacao.id'], ),
    sa.ForeignKeyConstraint(['respondido_por'], ['usuario.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('periodo_id', 'empresa_id', name='uq_resposta_ocupacao_periodo_empresa')
    )
    op.create_table('resultado_ocupacao',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('periodo_id', sa.Integer(), nullable=False),
    sa.Column('taxa_ponderada', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('total_respondentes', sa.Integer(), nullable=True),
    sa.Column('total_leitos_respondidos', sa.Integer(), nullable=True),
    sa.Column('perc_leitos_respondidos', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('diaria_media_ponderada', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('receita_estimada', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('calculado_em', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['periodo_id'], ['periodo_ocupacao.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('periodo_id')
    )
    op.create_table('avaliacao_atrativo',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('resposta_id', sa.UUID(), nullable=False),
    sa.Column('nome_atrativo', sa.String(length=120), nullable=False),
    sa.Column('nota', sa.SmallInteger(), nullable=True),
    sa.CheckConstraint('nota BETWEEN 1 AND 5', name='ck_avaliacao_atrativo_nota'),
    sa.ForeignKeyConstraint(['resposta_id'], ['resposta_demanda.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('avaliacao_servico',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('resposta_id', sa.UUID(), nullable=False),
    sa.Column('dimensao', sa.String(length=40), nullable=False),
    sa.Column('nota', sa.SmallInteger(), nullable=True),
    sa.CheckConstraint('nota BETWEEN 1 AND 5', name='ck_avaliacao_servico_nota'),
    sa.ForeignKeyConstraint(['resposta_id'], ['resposta_demanda.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('demanda_estadia',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('resposta_id', sa.UUID(), nullable=False),
    sa.Column('estado_residencia', sa.String(length=50), nullable=True),
    sa.Column('cidade_residencia', sa.String(length=80), nullable=True),
    sa.Column('data_chegada', sa.DateTime(), nullable=True),
    sa.Column('data_partida', sa.DateTime(), nullable=True),
    sa.Column('pernoites', sa.Integer(), nullable=True),
    sa.Column('meio_hospedagem', sa.String(length=60), nullable=True),
    sa.Column('acompanhantes_tipo', sa.String(length=40), nullable=True),
    sa.ForeignKeyConstraint(['resposta_id'], ['resposta_demanda.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('resposta_id')
    )
    op.create_table('demanda_perfil_socioeconomico',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('resposta_id', sa.UUID(), nullable=False),
    sa.Column('genero', sa.String(length=30), nullable=True),
    sa.Column('faixa_etaria', sa.String(length=20), nullable=True),
    sa.Column('renda_familiar', sa.String(length=40), nullable=True),
    sa.Column('gasto_medio_diario', sa.String(length=40), nullable=True),
    sa.ForeignKeyConstraint(['resposta_id'], ['resposta_demanda.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('resposta_id')
    )
    op.create_table('demanda_satisfacao',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('resposta_id', sa.UUID(), nullable=False),
    sa.Column('voltaria', sa.Boolean(), nullable=True),
    sa.Column('indicaria', sa.Boolean(), nullable=True),
    sa.Column('nps_recomendacao', sa.SmallInteger(), nullable=True),
    sa.Column('nota_destino', sa.SmallInteger(), nullable=True),
    sa.CheckConstraint('nota_destino BETWEEN 0 AND 10', name='ck_demanda_satisfacao_nota_destino'),
    sa.CheckConstraint('nps_recomendacao BETWEEN 0 AND 10', name='ck_demanda_satisfacao_nps'),
    sa.ForeignKeyConstraint(['resposta_id'], ['resposta_demanda.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('resposta_id')
    )
    op.create_table('demanda_viagem',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('resposta_id', sa.UUID(), nullable=False),
    sa.Column('motivo_viagem', sa.ARRAY(sa.Text()), nullable=True),
    sa.Column('transporte_utilizado', sa.String(length=60), nullable=True),
    sa.Column('considerou_outro_destino', sa.Boolean(), nullable=True),
    sa.Column('destinos_concorrentes', sa.ARRAY(sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['resposta_id'], ['resposta_demanda.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('resposta_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('demanda_viagem')
    op.drop_table('demanda_satisfacao')
    op.drop_table('demanda_perfil_socioeconomico')
    op.drop_table('demanda_estadia')
    op.drop_table('avaliacao_servico')
    op.drop_table('avaliacao_atrativo')
    op.drop_table('resultado_ocupacao')
    op.drop_table('resposta_ocupacao')
    op.drop_table('resposta_demanda')
    op.drop_table('respondente_pesquisa')
    op.drop_table('periodo_ocupacao')
    op.drop_table('formulario_versao')
    op.drop_table('empresa')
    op.drop_table('audit_log')
    op.drop_table('usuario')
    op.drop_table('categoria_empresa')
    # ### end Alembic commands ###
